import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { QueryClient,QueryClientProvider } from '@tanstack/react-query';
import { WagmiProvider } from 'wagmi';
import { wagmiConfig } from './lib/wagmi';
import { AuthProvider } from './components/AuthProvider';
import { App } from './App';
import './styles.css';
const queryClient=new QueryClient();
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><WagmiProvider config={wagmiConfig}><QueryClientProvider client={queryClient}><BrowserRouter><AuthProvider><App/></AuthProvider></BrowserRouter></QueryClientProvider></WagmiProvider></React.StrictMode>);
