import { useEffect,useState } from 'react';
import { api,jsonBody } from '../lib/api';
import type { Project } from '../lib/types';
import { Badge,Card,Empty,PageTitle } from '../components/Ui';
const slugify=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'github-project';
export function GitHubDiscovery(){
  const [repos,setRepos]=useState<any[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const loadProjects=()=>api<Project[]>('/projects').then(setProjects);useEffect(()=>{void loadProjects()},[]);
  const discover=async()=>{setBusy(true);setError('');try{setRepos(await api('/github/discover'))}catch(e:any){setError(e.message)}finally{setBusy(false)}};
  const associate=async(repoId:string,projectId:string)=>{if(!projectId)return;await api(`/github/repositories/${repoId}/associate`,{method:'POST',body:jsonBody({projectId})});setRepos(x=>x.filter(r=>r.id!==repoId))};
  const ignore=async(id:string)=>{await api(`/github/repositories/${id}/ignore`,{method:'POST',body:'{}'});setRepos(x=>x.filter(r=>r.id!==id))};
  const createProject=async(r:any)=>{try{const created:any=await api('/projects',{method:'POST',body:jsonBody({name:r.name,slug:slugify(r.name),kind:'project',summary:r.purpose||`Imported from ${r.owner}/${r.name}`})});await associate(r.id,created.id);await loadProjects()}catch(e:any){setError(e.message)}};
  const createComponent=async(r:any)=>{try{const created:any=await api('/components',{method:'POST',body:jsonBody({name:r.name,slug:slugify(r.name),category:'repository',purpose:r.purpose||`Reusable concept referenced by ${r.owner}/${r.name}`})});await api(`/github/repositories/${r.id}/associate`,{method:'POST',body:jsonBody({componentId:created.id})});setRepos(x=>x.filter(x=>x.id!==r.id))}catch(e:any){setError(e.message)}};
  return <><PageTitle title="GitHub discovery" subtitle="The server-side GitHub App can discover repositories. Nothing is attached or made public without your decision." actions={<button className="button primary" onClick={discover} disabled={busy}>{busy?'Checking GitHub…':'Discover repositories'}</button>}/>{error&&<div className="notice warn">{error}</div>}<Card>{repos.length?<div className="resource-list">{repos.map(r=><div className="repo-discovery" key={r.id}><div><strong>{r.owner}/{r.name}</strong><div className="row-sub">{r.visibility} · {r.default_branch}</div>{r.purpose&&<p className="muted">{r.purpose}</p>}<a href={r.html_url} target="_blank">{r.html_url}</a></div><div className="repo-actions"><button className="button" onClick={()=>createProject(r)}>New project</button><button className="button" onClick={()=>createComponent(r)}>New component</button><select defaultValue="" onChange={e=>associate(r.id,e.target.value)}><option value="" disabled>Attach to project…</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="button ghost" onClick={()=>ignore(r.id)}>Ignore</button><Badge>new</Badge></div></div>)}</div>:<Empty>Run discovery to find repositories not yet assigned to a project or component.</Empty>}</Card></>;
}
