import { useEffect,useMemo,useState } from 'react';
import { api,jsonBody } from '../lib/api';
import { Badge,Card,Empty,PageTitle } from '../components/Ui';

type Row={project_id:string;name:string;kind:string;status:string;published:boolean;featured:boolean;sort_order:number;title:string;public_slug:string};
export function Publishing(){
  const [rows,setRows]=useState<Row[]>([]); const [busy,setBusy]=useState(''); const [drag,setDrag]=useState<string>(''); const [importMsg,setImportMsg]=useState(''); const [error,setError]=useState('');
  const load=()=>api<Row[]>('/publishing').then(setRows); useEffect(()=>{void load()},[]);
  const kinds=useMemo(()=>Array.from(new Set(rows.map(r=>r.kind))),[rows]);
  const move=(kind:string,target:string)=>{if(!drag||drag===target)return;setRows(current=>{const same=current.filter(r=>r.kind===kind);const rest=current.filter(r=>r.kind!==kind);const from=same.findIndex(r=>r.project_id===drag),to=same.findIndex(r=>r.project_id===target);if(from<0||to<0)return current;const [item]=same.splice(from,1);same.splice(to,0,item);return [...rest,...same.map((r,i)=>({...r,sort_order:i}))];});};
  const save=async(kind:string)=>{setBusy(kind);setError('');try{const orderedProjectIds=rows.filter(r=>r.kind===kind).sort((a,b)=>a.sort_order-b.sort_order).map(r=>r.project_id);await api('/publishing/order',{method:'PUT',body:jsonBody({kind,orderedProjectIds})});await load();}catch(e:any){setError(e.message)}finally{setBusy('')}};
  const importLegacy=async(file?:File)=>{if(!file)return;setBusy('import');setError('');setImportMsg('');try{const text=await file.text();const payload=JSON.parse(text);const result=await api<any>('/import/inhaus-projects',{method:'POST',body:jsonBody(payload)});setImportMsg(`Imported ${result.total}: ${result.created} project shells created, ${result.updated} existing records updated.`);await load();}catch(e:any){setError(e.message)}finally{setBusy('')}};
  return <><PageTitle title="Public publishing" subtitle="The public site receives only the explicit public projection. Drag entries to set their order; private project data never enters this feed."/>
    <Card><div className="card-head"><div><h2>Bootstrap from the existing InHaus site</h2><p className="muted">Upload the current public <code>projects.json</code> once to create/update project shells and public profiles without retyping the existing portfolio.</p></div><label className="button">{busy==='import'?'Importing…':'Import projects.json'}<input hidden type="file" accept=".json,application/json" disabled={!!busy} onChange={e=>void importLegacy(e.target.files?.[0])}/></label></div>{importMsg&&<div className="notice">{importMsg}</div>}{error&&<div className="notice warn">{error}</div>}</Card>
    {kinds.length?kinds.map(kind=><Card key={kind}><div className="card-head"><div><h2>{kind==='game'?'Games':kind[0].toUpperCase()+kind.slice(1)}</h2><p className="muted">Drag to reorder, then save.</p></div><button className="button primary" disabled={!!busy} onClick={()=>save(kind)}>{busy===kind?'Saving…':'Save order'}</button></div><div className="resource-list">{rows.filter(r=>r.kind===kind).sort((a,b)=>a.sort_order-b.sort_order).map((r,i)=><div key={r.project_id} draggable onDragStart={()=>setDrag(r.project_id)} onDragOver={e=>e.preventDefault()} onDrop={()=>move(kind,r.project_id)} className="publish-row"><span className="drag-handle">⋮⋮</span><strong>{i+1}. {r.title||r.name}</strong><span className="row-sub">/{r.public_slug} · source: {r.name}</span><Badge tone={r.published?'public':'private'}>{r.published?'published':'unpublished'}</Badge>{r.featured&&<Badge>featured</Badge>}</div>)}</div></Card>):<Empty>No public project/game profiles exist yet. Create one from a project's Public tab or import the existing public projects.json.</Empty>}
  </>;
}
